### ISSUE TITLE
Résoudre les alertes dependabots

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1019]
Faire une passe sur l'ensemble des projets udata et ses plugins et résoudre les alertes.

Pour les cas difficiles, ne pas hésiter à créer des sous-tickets dédiés !

- [ ] résoudre les alertes dependabots sur udata
- [x] résoudre les alertes dependabots sur udata-front
- [x] #1048
- [ ] résoudre les alertes dependabots sur udata-ckan
- [ ] résoudre les alertes dependabots sur udata-ods
- [ ] résoudre les alertes dependabots sur udata-search-service
- [x] #1047
- [ ] résoudre les alertes dependabots sur udata-metrics
- [ ] résoudre les alertes dependabots sur udata-transport
- [x] #1049

**Comment by agarrone** [comment]
@maudetes d'actu ?
