### ISSUE TITLE
Investiguer sur les mails

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1025]
Quels mails sont envoyés aux membres de l’organisation aujd ? 
A quel type de membres ? 
Lesquels ne sont pas envoyés ? 

Voir pour contexte : 
- https://www.notion.so/apigouv/Mails-transactionnels-Infolettre-3ee1b4d2b79c4d5697fae67e187617d3
- #498

**Comment by maudetes** [comment]
# Dataset
* discussion (nouvelle, commentaire ou close) -> membres ou user
* [désactivé] rappel mise à jour rapport à la fréquence annoncée -> membres
* [désactivé] nouvelle réutilisation -> members ou user

# Organisation
* [[bug](https://errors.data.gouv.fr/organizations/sentry/issues/222/?query=is%3Aunresolved+notify_membership_request&referrer=issue-stream&statsPeriod=14d)]  membership request (demande, acceptée, refusée) -> admins
* ajout de badge (public service + certified?) -> membres

# User
* les mails de sécu (validation, perte de mdp, etc.)
* suppression de compte -> user

Je n'ai pas retrouvé de trace d'envoie de mails lors d'abonnement (follow), quand bien même les templates existent.

**Comment by agarrone** [comment]
Investigation done
