### ISSUE TITLE
Activer la preview et explore sur les jeux de données ODS

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1063]
S'assurer en amont et par la suite qu'il y a de la marge niveau ressources sur csvapi et explore.
Peut-être que désactiver le plugin ODS suffit.

**Comment by agarrone** [comment]
On est good là dessus non @maudetes ?

**Comment by maudetes** [comment]
Yes! :rocket: C'était une des conséquences de la [migration à DCAT](https://github.com/opendatateam/udata-ods/pull/247)
