### ISSUE TITLE
Création d'une liste de contacts organisations - pour Brevo (email 2 - maj de CGU)

### ISSUE THREAD

**Issue by mikoa9** [datagouv/data.gouv.fr#1127]
Créer une liste de contacts qui sera ensuite importée dans l'outil emailing Brevo.
Cible : toutes les orga ici : https://airtable.com/appuaB2XsPhF7vMNx/tbl0w8tkaXMtntWwm/viwa23IkngtwENiKt?blocks=hide
Email : MAJ des CGU (envoi autour de Août/septembre)

Informations souhaitées dans le fichier csv ou xlsx (par colonne)  : 
- Nom de l'organisation / nom User
- URL de l'organisation / URL user
- Type de l'organisation : "OK",  "à certifier", "à supprimer", "à contacter" + tous les "users".
- Email Admin 1
- Email Admin 2
- Email Admin x

pas besoin finalement les organisations que les users/ perica

Lien du projet : https://www.notion.so/apigouv/Planification-des-emails-destination-des-organisations-b71a45772fad44eaa05b31ec18a303c5

On en parle avant :)

Merci
Clarisse

**Comment by agarrone** [comment]
Done il me semble ne pas hésiter à rouvrir si besoin.
