### ISSUE TITLE
Discuter de la mise en place d'un dashboard interne (indicateurs data.gouv.fr)

### ISSUE THREAD

**Issue by mikoa9** [datagouv/data.gouv.fr#1149]
Hello,

On souhaiterait mettre en place un dashboard en interne pour pouvoir suivre certains indicateurs de data/gouv.fr 
Voir la liste, objectifs et questions ici :
https://www.notion.so/apigouv/Mise-en-place-d-un-dashboard-de-suivi-des-indicateurs-2d8c8b223d7c47ab80d7a61aeaf1da4f

On pourrait dans un premier temps commencer par les indicateurs du point 1.Idées de sujets d’articles, avec les Top orga/ JDD etc.

On en reparle :)

Merci
Clarisse

**Comment by mikoa9** [comment]
pour info @agarrone @thanhhale7

**Comment by agarrone** [comment]
Done
