### ISSUE TITLE
Mettre la marianne comme image google par défaut

### ISSUE THREAD

**Issue by geoffreyaldebert** [datagouv/data.gouv.fr#1162]
Changer l'image par défaut que lit Google pour data.gouv.fr et la remplacer par la marianne. 

Voir : https://www.google.com/search?q=data+gouv

**Comment by geoffreyaldebert** [comment]
On pourrait également en profiter pour essayer de modifier le titre de la page et sa description. 

> data.gouv.fr. Accueil 

c'est un peu léger :)

**Comment by maudetes** [comment]
C'est la favicon du site. A voir si on veut faire ce changement : https://github.com/etalab/data.gouv.fr/issues/279.
Pour la description, j'avoue qu'on peut la retravailler un peu :p

**Comment by geoffreyaldebert** [comment]
@agarrone pourquoi on ne voulait pas la marianne en favicon ? pour comprendre ? Je trouve ça plus clair qu'un simple "D" non ?

**Comment by agarrone** [comment]
C'était pour ne pas rajouter à la reception de data.gouv.fr comme d'un truc "officiel" où il n'est pas légitime de publier ou d'interargir. Garder l'aspect ouvert et communautaire de data.gouv.fr
