### ISSUE TITLE
Rechercher un utilisateur à l'aide d'une adresse email (admin data.gouv.fr)

### ISSUE THREAD

**Issue by mikoa9** [datagouv/data.gouv.fr#1164]
Dans le cadre du support, il serait intéressant de pouvoir effectuer une recherche avec l'email de l'utilisateur dans l'administration de data.gouv.fr

Par exemple : faire la recherche dans le champ recherche au niveau de l'utilisateur et présenter uniquement le (les?) résultat(s) des utilisateurs avec cette adresse email.

Merci !

Clarisse

**Comment by agarrone** [comment]
Pris en compte dans la nouvel admin
