### ISSUE TITLE
Corriger l'affichage des titres formatés dans les descriptions des ressources

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1165]
Sur la description d'une ressource, la taille des titres est écrasée lors du rendu sur le front.
Voir par exemple sur https://demo.data.gouv.fr/fr/datasets/jeu-de-donnees-pour-audit-daccessibilite/#/resources/d5a5ebc1-efe9-4044-83e8-2d0023e21081 (en privé)

Remonté par https://support.etalab.gouv.fr/#ticket/zoom/61957

Edit : Nouveau [lien vers Figma](https://www.figma.com/design/t2el9byspyFX2A9Kuih1ls/%E2%9C%8D%EF%B8%8F-Formatage-Markdown?node-id=4-5&t=iCnG6JqdYOUOpaW5-1)

**Comment by agarrone** [comment]
Vous en pensez quoi @maudetes @nicolaskempf57 ?

**Comment by nicolaskempf57** [comment]
C'est un bug lié à l'affichage du markdown des ressources.

Sur les maquettes la description (et les titres, etc) des ressources était plus petite que la description du dataset, j'ai diminué la taille de tous les éléments pour qu'ils s'affichent en plus petit mais ça a dû prendre le pas sur les tailles des titres.

Le plus simple serait d'afficher toujours le contenu markdown de la même façon sans tenir compte du fait que ce soit pour une ressource, un dataset, une page, etc.

**Comment by agarrone** [comment]
Ca ne semble pas critique perso

**Comment by maudetes** [comment]
Pas très prio, après si @nicolaskempf57, tu veux l'embarquer avec https://github.com/datagouv/data.gouv.fr/issues/1188, why not

**Comment by nicolaskempf57** [comment]
> Le plus simple serait d'afficher toujours le contenu markdown de la même façon sans tenir compte du fait que ce soit pour une ressource, un dataset, une page, etc.

Si on part là dessus, je peux complètement le faire le même temps que le nouveau viewer markdown oui

**Comment by agarrone** [comment]
Attention quand même j'ai peur que ça fasse des affichages chelou avec des titres énormes par rapport à "nos" titres

**Comment by nicolaskempf57** [comment]
Est-ce que vous voulez en profitez pour faire une passe Produit & Design sur la façon dont on affiche les contenus markdown (principalement les titres j'imagine) sur les descriptions et les ressources ?

Comme ça on corrige avec quelque chose de propre

**Comment by agarrone** [comment]
Yes je l'ajoute à notre todo
