### ISSUE TITLE
Forcer le lazy loading des images des descriptions markdown d'udata-front

### ISSUE THREAD

**Issue by nicolaskempf57** [datagouv/data.gouv.fr#1188]
Les producteurs et les réutilisateurs peuvent ajouter des images aux descriptions des jeux de données, fichiers et réutilisations. Afin d'avoir un fonctionnement optimal et équivalent aux images présentes dans le code source, il faudrait forcer le lazy loading des `<img>`.

**Comment by nicolaskempf57** [comment]
J'ai un résultat satisfaisant sur les affichages markdown en JS mais certains sont fait en jinja. J'essaie de faire une solution unique pour une meilleure compatibilité.

**Comment by agarrone** [comment]
@nicolaskempf57 tjr d'actu notamment avec le nouvel éditeur prévu ?
