### ISSUE TITLE
clean composants datagouvfr-components

### ISSUE THREAD

**Issue by geoffreyaldebert** [datagouv/data.gouv.fr#1265]

**Comment by nicolaskempf57** [comment]
Update 30/01 : le package est maintenant merge sur master, reste encore https://github.com/etalab/udata-front/pull/346 puis merge master sur chaque PR, ajouter la config Storybook et utiliser les composants du package dans udata-front

**Comment by Jorek57** [comment]
Update: Quality, ReadMore, InformationPanel Components are in review, only the DatasetCard is left to do

**Comment by nicolaskempf57** [comment]
Update: Quality, ReadMore, InformationPanel Components are merged, only the DatasetCard is left to review
