### ISSUE TITLE
Rajouter une fonctionnalité d'archivage des reuses

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1273]
Similairement à ce qui est fait sur les Datasets, rajouter un champ datetime `archived`, renseignable par API.
Contrairement aux datasets, on continuerait d'indexer les réutilisations archivés, mais un comportement front pourrait être adapté (au niveau du lien en particulier) pour les réutilisations archivées.

Voir l'exemple de la métadonnée définie dans le modèle côté dataset : https://github.com/opendatateam/udata/blob/9aa0fca0318479a3a065f2cf18948dc083fdfb0c/udata/core/dataset/models.py#L493

Voir issue en lien : https://github.com/datagouv/data.gouv.fr/issues/1393

**Comment by bolinocroustibat** [comment]
Closes https://github.com/opendatateam/udata/pull/3088
