### ISSUE TITLE
Dashboard de suivi support

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1276]
Coût à investiguer en fonction de la mise en place d'un autre outil

### Optimisation suivi Matomo 
- [ ] Mise en place d'évènement pour suivre le parcours suivi par les utilisateurs en fonction de leur provenance

### Mise en place d'un dashboard 
- [ ] Mise en place d'un dashboard de suivi avec les indicateurs suivants (taux de visites support/taux de visites data.gouv.fr ; nb de ticket ou clic sur le bouton envoyer/nb de visites sur la page support ; ticket HS/nb tickets total
- [ ] Mise en place d'un bot mattermost

**Comment by mikoa9** [comment]
@Pierlou matomo : https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=109&period=range&date=previous30#?period=range&date=previous30&idSite=109&category=Dashboard_Dashboard&subcategory=1

**Comment by mikoa9** [comment]
@Pierlou https://www.notion.so/apigouv/Support-Action-Items-d74e220c6343470e8fc1f50a62256650?p=2340a00346064f4cae22ba7c01bbbbf8&pm=s

**Comment by agarrone** [comment]
Done sur monitor
