### ISSUE TITLE
[META] Gestion des droits des utilisateurs au sein d'une organisation

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1282]
## Problématique

Les membres d’organisations sur data.gouv.fr rencontre plusieurs problèmes notamment : 

- Notifications envoyés à tout les membres d’une organisation pour un jeux de données qui concerne peu d’utilisateurs
- Pas de possibilité de gestion fins des droits : un éditeur a le droit sur toute l’administration
- Pas de possibilité de catégoriser les jeux de données en sous producteurs, services
- Pas de possibilité de créer des liens entre organisations
- Pas de possibilité d’inviter des utilisateurs qui n’ont pas de compte data.gouv.fr
- Pas de possibilité de savoir qui a fait quoi au sein d’une organisation

![Image](https://github.com/etalab/data.gouv.fr/assets/60264344/0f3405f6-f754-477d-b297-e9f6cd8aa0ce)

Voir également les besoins côté transport.data.gouv.fr : https://github.com/etalab/data.gouv.fr/discussions/1200#discussioncomment-7854294

## Solution pressentie

Permettre aux administrateurs d’organisations de créer des équipes au sein de leur organisations

Donc 3 types de droits 

- Admin
- Editeur : de toute l’organisation
- Editeur : d’une équipe en particulier

Pour l’utilisateur il sera possible de voir l’équipe et l’organisation qui a publié les données 

## Benchmark & analyse concurrentielle

Le modèle de Github et de Figma semblent être des pistes interessantes

**Comment by maudetes** [comment]
## Discussion produit pour le passage à un fonctionnement avec Teams

Il faut prendre en compte le fait que de nombreuses orgas ont 1 ou 2 membres et ne veulent pas nécessairement gérer les teams.

1. Une orga = une team englobante (tous les membres y sont)
2. Rien qui change, team optionnel.
    * Quand un JDD a une team, seule la team peut modifier. Si un JDD n'en a pas par contre, tout le monde peut modifier.
        * Moins de protection, car ouvert par défaut. Comportement non évident.
    * A partir d'un passage au mode team (action explicite), les teams sont nécessaires pour toute l'orga
        * Au moment de création de teams, flow onboarding pour accompagner (possibilité de faciliter team par défaut). Il faut répartir les JDDs dans des teams et les membres dans des teams
        * Attention au moissonnage, les nouveaux JDDs créés seront sans team ? Associer une team dédiée aux nouveaux JDDs par moissonnage


## Decision

On partirait pour la solution d'activation explicite d'un mode team par les orgas volontaires.
TODO :
 * maquette produit, onboarding teams et membres (et gestion)
 * côté back gérer les permissions des orgas avec ou sans teams

**Comment by agarrone** [comment]
Investigation terminé pour cette phase.
