### ISSUE TITLE
Rajouter une configuration ReadTheDocs

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1320]
Depuis septembre 2023, la présence d'un fichier .readthedocs.yaml est nécessaire dans un repo.
Voir [les builds associés](https://readthedocs.org/projects/udata/builds/) [ou ici](https://app.readthedocs.org/projects/udata/builds/?utm_source=udata&utm_content=flyout).

![Image](https://github.com/etalab/data.gouv.fr/assets/28541902/39e04b78-cc73-4bdb-b058-e5944db8ee4b)

Voir la documentation pour ce fichier : https://docs.readthedocs.io/en/stable/config-file/index.html.

Attention, le build semblait échouer auparavant pour des raisons de version.
Probable que l'erreur n'apparaisse pas si on passe par la config readthedocs. 🤞 
```
AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Comment by bolinocroustibat** [comment]
D'après la doc, le fichier `.readthedoc.yaml` est nécessaire depuis septembre 2023, ça explique pourquoi

**Comment by bolinocroustibat** [comment]
PR liée: https://github.com/opendatateam/udata/pull/3077

Est-ce que ça doit être basé sur `dev` ou bien `master`?
