### ISSUE TITLE
Pas de redirection en cas de trailing / manquant sur la route `/zone/<id>`

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1338]
Enquêter sur l'absence de redirection sur cette route, alors que toutes les autres routes font une redirection en rajoutant un trailing slash et évitent donc une 404.
Exemple: https://www.data.gouv.fr/api/1/spatial/zone/fr:departement:17 retourne  une 404.

Reproduit aussi sur https://www.data.gouv.fr/api/1/spatial/zone/fr:departement:17/datasets

**Comment by ThibaudDauce** [comment]
Le problème vient du fait que l'on match un `path` pour les zones IDs dans l'URL (et donc que le converter prend en compte les `/`). Est-ce qu'il peut y avoir des `/` dans les IDs des zones ? Si oui je suis pas sûr que l'on puisse faire quelque chose pour changer ça. Si non on peut enlever les converter `path` pour mettre des converters basiques et ça corrige le problème.

**Comment by ThibaudDauce** [comment]
La question se pose également pour les `level`. Voir https://github.com/opendatateam/udata/pull/3045
