### ISSUE TITLE
Problème de rerooting vers l'explore sur les gros fichiers

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1341]
Sur les jeux de données comme les personnes décédées ou le SIRET (fichiers lourd et très souvent consommé) le bouton explore général est confusant car il permet d'explorer un fichier annexe comme le fichier des métadonnées par exemple plutôt que le fichier principal qui n'est pas explorable (trop lourd ou pas le bon format).

### Propositions 
1. Afficher le bouton explore uniquement si il existe un fichier de type _fichier principal_ explorable (semble difficile car le typage des fichiers n'est pas fait voir par exemple [ce fichier](https://www.data.gouv.fr/fr/datasets/fichier-des-personnes-decedees/#/resources/7bcdfa57-dc50-43a8-beb6-6c76537e7057))
2. Ne plus afficher ce bouton : ça semblait être une bonne idée mais en pratique il y a trop de cas particuliers pour que cela soit bien compris ?

**Comment by agarrone** [comment]
Avis @geoffreyaldebert @maudetes @nicolaskempf57 @rkalfane

**Comment by nicolaskempf57** [comment]
> * Afficher le bouton explore uniquement si il existe un fichier de type _fichier principal_ explorable (semble difficile car le typage des fichiers n'est pas fait voir par exemple [ce fichier](https://www.data.gouv.fr/fr/datasets/fichier-des-personnes-decedees/#/resources/7bcdfa57-dc50-43a8-beb6-6c76537e7057))

@agarrone Ça me parait un bon compromis, sachant que par défaut les fichiers sont en type "principal". Si un producteur veut améliorer l'expérience il a juste à utiliser les fonctions proposées par la plateforme.

Je trouve que désactiver le bouton cache vraiment la fonctionnalité ("scroller dans la page", "chercher le fichier dans la liste", éventuellement "changer de page", "voir les données" et enfin "explorer les données"). La question produit / design à laquelle je ne peux pas vraiment répondre c'est "est-ce qu'on veut favoriser l'accès direct à explore ? Ou la préviz sur datagouv?"

**Comment by agarrone** [comment]
J'ai l'impression que bien souvent un accès direct à l'explore peut être complexe à comprendre pour l'utilisateur novice.
Le "forcer" à passer par les ressources permet peut être d'aider à comprendre la structure des données. 
En revanche pour tout ce qui est ODS c'est pertinent. 
Comme d'habitude, pas simple de choisir face à la diversité des cas. 
Je suis OK pour n'afficher le bouton que si un des fichiers principaux est explorable.
