### ISSUE TITLE
Fix locale not working in plugin in udata-tabular-preview

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1360]
* See https://github.com/opendatateam/udata-tabular-preview/pull/37, `formatDate` did not use current locale in udata-tabular-preview plugin.
See https://github.com/opendatateam/udata-tabular-preview/pull/33#issuecomment-2004539538, some translation did not seem to get properly loaded here.

Might be made irrelevant due to https://github.com/datagouv/data.gouv.fr/issues/1360.

**Comment by nicolaskempf57** [comment]
Est-ce qu'on en profite pour basculer les composants dans datagouv/components ?
