### ISSUE TITLE
Rajouter métadonnées HVD dans l'export DCAT

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1371]
Voir [la spec DCAT-AP HVD](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/).

- [x] **PRIORITAIRE** Métadonnées HVD obligatoires à rajouter :
* dcatap:applicableLegislation
* dcatap:hvdCategory
* dcat:contactPoint
Faut-il faire un endpoint dédié ?
Ou permettre de rajouter un filtre `tag=hvd` sur https://www.data.gouv.fr/api/1/site/catalog.xml?
-> done avec un filtre :heavy_check_mark: 
- [x] Modéliser les dcat:DataServices
- [x] #1519
* A rajouter dans l'export rdf du dataset & du dataservice. Lignées concernées côté dataset : https://github.com/opendatateam/udata/blob/a94fcfdcb35847113e7ca66a161b601a24fca75c/udata/core/dataset/rdf.py#L194
* Specs : https://w3c.github.io/dxwg/dcat/#Property:resource_contact_point et https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.contactpoint
- [x] #1553

**Comment by magopian** [comment]
Je ferme ce ticket maintenant qu'on a mergé la dernière modif listée https://github.com/opendatateam/udata/pull/3187
