### ISSUE TITLE
Intégrer la carte dataservice sur la page jeu de données

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1378]
Voir le figma : https://www.figma.com/design/9Ai2c1JrRyFNKDSJOXN9wM/%F0%9F%92%BB-Api-et-donn%C3%A9es-restreintes?node-id=404-11310&t=Ia412XMtTeJYbq3l-4

**Comment by ThibaudDauce** [comment]
Done in https://github.com/datagouv/udata-front/pull/476
