### ISSUE TITLE
Corriger le permalink des ressources communautaires

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1380]
Exemple de lien vers une ressource communautaire non fonctionnel : https://www.data.gouv.fr/fr/datasets/resultats-provisoires-des-elections-europeennes-du-9-juin-2024/#/resources/2d97ecd3-a39d-4e0e-8eb0-a0d5a01ea588

En effet l'url contient `/resources/` et non pas `/community-resources/`

**Comment by nicolaskempf57** [comment]
@maudetes @agarrone Je ne suis plus sûr de ce qu'on avait dit pour ce ticket. Est-ce qu'on veut ?
1. supprimer le lien quand il s'agit d'une ressource communautaire
2. ajouter dans udata-front la gestion des liens pour les ressources communautaires

**Comment by maudetes** [comment]
dans l'idéal 2 oui je dirais :)

**Comment by nicolaskempf57** [comment]
Super ! On fait ça

**Comment by maudetes** [comment]
@nicolaskempf57, je vois que tu avais fait la modif 1. dans la PR de preview : https://github.com/datagouv/udata-front/pull/433/files#diff-90a02b3f108072a3b5c005ee31701a515177e06358cd842596ed5aa978cd9b9cL309-R309.

Ok pour faire une PR pour ré-ajouter le lien avec permalien pour les ressources communautaires (l'otpion 2.) ?

**Comment by nicolaskempf57** [comment]
Oui complètement, je pense que j'ai fait la modification comme j'étais dans le fichier et que dans tous les cas le lien est faux
