### ISSUE TITLE
Changer le format de retour de l'API des motifs de signalements

### ISSUE THREAD

**Issue by nicolaskempf57** [datagouv/data.gouv.fr#1391]
L'API des motifs de signalement (`/api/1/reports/reasons/`) renvoie un dictionnaire de motifs de signalement sous la forme :

```
{
  "explicit_content": "Explicit content",
  "illegal_content": "Illegal content",
  "others": "Others",
  "personal_data": "Personal data",
  "security": "Security",
  "spam": "Spam"
}
```

Il faudrait à la place que ce soit renvoyé sous la forme d'un tableau de la forme :

```
[
    {"value": "explicit_content", "label": "Explicit content"},
    ...
]
```

**Comment by bolinocroustibat** [comment]
PR: https://github.com/opendatateam/udata/pull/3078
