### ISSUE TITLE
udata: Permettre l'archivage/désarchivage des jeux de données et réutilisations depuis l'admin

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1393]
Aujourd'hui seul le moissonnage (ou les power users par API) permet d'archiver un jeu de données.
Cette fonctionnalité pourrait pourtant être pertinente pour les jeux de données hors moissonnage. Cela rendrait les utilisateurs plus autonome par ailleurs.

Rajouter cette fonctionnalité sur les réutilisations suite à https://github.com/datagouv/data.gouv.fr/issues/1273.

Rajouter un bouton dans l'admin pour permettre archivage/désarchivage.
Par exemple dans les actions sur le jeu de données :
![Image](https://github.com/datagouv/data.gouv.fr/assets/28541902/f5351854-7898-4cf1-94f9-85c63677eef6)

**Comment by maudetes** [comment]
Est-ce que ce serait bon pour toi @agarrone ? Ca irait avec https://github.com/datagouv/data.gouv.fr/issues/1273

**Comment by agarrone** [comment]
Yes, il faudra l'ajouter aux guides :)

**Comment by bolinocroustibat** [comment]
Done and merged for the reuses: https://github.com/opendatateam/udata/pull/3088

Has the same been done for the datasets yet?

**Comment by maudetes** [comment]
Only the backend exists for datasets but the button is still missing from the admin!

**Comment by bolinocroustibat** [comment]
> Only the backend exists for datasets but the button is still missing from the admin!
In that case I can easily do that, here is the PR: https://github.com/datagouv/data.gouv.fr/issues/1393

**Comment by bolinocroustibat** [comment]
@maudetes We can close that one, right?
