### ISSUE TITLE
Élections et handicap

### ISSUE THREAD

**Issue by egassie** [datagouv/data.gouv.fr#1394]
Bonjour
dans les données sur les élections, j'aimerais pouvoir trouver le vote par statut de handicap, mais aussi par genre agrégé au niveau national ou bien désagrégé
J'aimerais aussi voir le vote par tranche d'âge âge et par tranche de revenus
En vous remerciant
Cordialement
Esmeralda Gassie

**Comment by mikoa9** [comment]
Bonjour Esmeralda,

Je vous invite à transmettre directement votre message sur notre support, pour ce type de demande : https://support.data.gouv.fr/
Merci par avance !
