### ISSUE TITLE
MEP des indicateurs des signalement (Dash)

### ISSUE THREAD

**Issue by mikoa9** [datagouv/data.gouv.fr#1419]
Ajouter un graphique dans le dashboard Dash pour suivre les signalements de contenus, avec ces infos :

- Nombre de contenus signalés selon la catégorie/type de signalement (histogramme à barre compilé) en ajoutant les valeurs, y compris le total

—> à ajouter dans un nouvel onglet, ou dans onglet support et renommer "support et signalement"

**Comment by Pierlou** [comment]
Done ✅
