### ISSUE TITLE
Schémas non-visibles dans le filtre des jeux de données

### ISSUE THREAD

**Issue by Pierlou** [datagouv/data.gouv.fr#1421]
## Description du bug
Certains schémas n'apparaissent pas dans le dropdown de filtre de https://www.data.gouv.fr/fr/datasets/, notamment [l'indice de réparabilité](https://schema.data.gouv.fr/etalab/schema-indice-reparabilite/) et [les indices de durabilité](https://schema.data.gouv.fr/etalab/schema-indice-durabilite/). Ils sont pourtant bien visibles lors de la création d'une ressource.
La source est la variable `schema_catalogue_url` dans l'infra. 🙏

**Comment by maudetes** [comment]
On les retrouve bien en effet (sauf le datapackage, [qui est filtré](https://github.com/datagouv/data.gouv.fr/issues/1148)) dans https://www.data.gouv.fr/api/1/datasets/schemas/.
Je dirais à enquêter côté front ?

**Comment by nicolaskempf57** [comment]
Je pense que c'est un bug mis en lumière par notre modification du nombre d'éléments affichés dans la liste, il doit rechercher seulement dans ceux affichés et non dans toute la liste.
