### ISSUE TITLE
Créer un dataservice avec un contact_point ne renvoie pas les données du point de contact

### ISSUE THREAD

**Issue by nicolaskempf57** [datagouv/data.gouv.fr#1428]
## Description du bug
Quand on crée un dataservice avec un id comme contact_point, les données renvoyées contiennent la clef `contact_point` avec toutes les valeurs à `null`.

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Créer un dataservice avec un id comme contact_point
2. Constater que le retour contient `"contact_point": { "email": null, "id": null, "name": null },`
3. Faire une requête GET avec l'id du dataservice
4. Constater que les données du contact_point sont bien enregistrées

## Comportement attendu
Il faudrait que le retour de la requête POST soit cohérent avec celui des requêtes GET suivantes.

**Comment by ThibaudDauce** [comment]
Je ne comprends pas trop le problème, je viens d'écrire un test et ça semble fonctionner… Est-ce que tu peux me dire comment tu crées ton dataservice ?

Ci-dessous le test (je ne sais pas si j'ai oublié quelque chose…)

```
    def test_create_with_contact_point(self):
        contact_point = ContactPointFactory(email="john@example.org", name="John Doe")
        self.login()

        response = self.post(
            url_for("api.dataservices"),
            {
                "title": "My title",
                "base_api_url": "https://example.org",
                "contact_point": contact_point.id,
            },
        )
        self.assert201(response)
        self.assertEqual(response.json["contact_point"]["email"], "john@example.org")
        self.assertEqual(response.json["contact_point"]["name"], "John Doe")

        self.assertEqual(Dataservice.objects.count(), 1)

        dataservice = Dataservice.objects.first()
        self.assertEqual(dataservice.contact_point.name, "John Doe")
        self.assertEqual(dataservice.contact_point.email, "john@example.org")

        response = self.get(url_for("api.dataservice", dataservice=dataservice))
        self.assert200(response)
        self.assertEqual(response.json["contact_point"]["email"], "john@example.org")
        self.assertEqual(response.json["contact_point"]["name"], "John Doe")
  ```

**Comment by nicolaskempf57** [comment]
Fixed after updating my master branch

**Comment by maudetes** [comment]
A bug fixed before even being noticed :star_struck:
