### ISSUE TITLE
Rajouter un filtre type d'organisation à la recherche de données 

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1431]
[Antonin] Permettre de filtrer par type d’organisation (Association, Entreprise, Collectivité territoriale, Service public, utilisateur).

[Estelle] Permettre de filtrer les jeux de données, reuses, dataservices ainsi que les organisations sur les badges de leur organisation : association/company/etc **et** certified.

A faire sur les routes de liste (ex: `/api/1/datasets`) et search (ex: `/api/2/datasets/search`) sur les différents objets.

Exemple de call (wording non définitif) :

    /datasests/?org_badge=company
    /organizations/?badge=company

**Comment by nicolaskempf57** [comment]
Reopened for the front-end part
