### ISSUE TITLE
Gérer le cas de la disponibilité manquante sur la carte dataservice

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1435]
La disponibilité est affichée mais sans valeur dans ce cas-là.

![Image](https://github.com/user-attachments/assets/d022d322-74d5-45ca-a459-1da9ab8fb6a0)

Rajouter un wording si l'information est manquante ? cc @agarrone

**Comment by agarrone** [comment]
Inconnue / unknown ?
