### ISSUE TITLE
Fixes page jeux de données admin V1 

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1448]
# Jeux de données
- [x] Mélange de langues : certains titres de tableau et tooltips sont en français, d'autres en anglais.
- [ ] #1458
- [x] #1459
- [x] #1460
    - La largeur de la colonne des titres pourrait être légèrement réduite.
    - La largeur de la colonne "Statut" peut être réduite.
    - Les colonnes des métriques devraient avoir la même largeur.
    - La barre de score devrait occuper toute la largeur de sa cellule.
- [x] Fixer la hauteur des lignes pour qu'elle corresponde à l'espace nécessaire pour afficher un titre sur deux lignes, garantissant ainsi l'homogénéité.
- [x] #1461

**Comment by nicolaskempf57** [comment]
Le point restant est suivi dans son propre ticket
