### ISSUE TITLE
On ne peut plus restaurer de réutilisations

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1457]
Afin de restaurer une réutilisation, il suffisait de faire un PUT avec `deleted=null`.
Cela n'enlève plus l'information du champ deleted, ce qui laisse donc la reuse supprimée.

Cela est probablement dû à https://github.com/opendatateam/udata/pull/3066

**Comment by ThibaudDauce** [comment]
Already done in https://github.com/opendatateam/udata/pull/3141 :-)
