### ISSUE TITLE
Un empty state est manquant.

### ISSUE THREAD

**Issue by nicolaskempf57** [datagouv/data.gouv.fr#1461]

**Comment by agarrone** [comment]
Les empty states sont ici : https://www.figma.com/design/YbluH37N5lpcM0SgF65LdD/%E2%9A%99%EF%B8%8F-Administrations-et-modification-des-jeux-de-donn%C3%A9es?node-id=2192-19632&t=CbavLtvugXWg8mLl-4 :)
