### ISSUE TITLE
L'import de fixtures peut échouer sur un email dupliqué

### ISSUE THREAD

**Issue by magopian** [datagouv/data.gouv.fr#1466]
Problème visible épisodiquement dans la [CI de udata-front](https://app.circleci.com/pipelines/github/datagouv/udata-front/4696/workflows/5dc5f9ca-dc6d-4377-a604-06df989d43b5/jobs/27389?invite=true#step-105-40875_169).

Une piste à explorer : lors de la [création d'un message dans une discussion](https://github.com/opendatateam/udata/blob/master/udata/commands/fixtures.py#L222), on appelle [`get_or_create`](https://github.com/opendatateam/udata/blob/master/udata/commands/fixtures.py#L155), or ça [`remove_unwanted_keys`](https://github.com/opendatateam/udata/blob/master/udata/commands/fixtures.py#L81) qui de son côté, pour `posted_by`, supprime l'adresse email.

Donc on ne va jamais pouvoir `get`, et on va sans cesse essayer de `create`, et on se retrouve alors parfois avec une limite de `UserFactory` qui réutiliserai le même email ?

Voici la doc de [factoryboy sur les séquences](https://factoryboy.readthedocs.io/en/stable/index.html#sequences)

Tout ça est à investiguer et valider.

**Comment by nicolaskempf57** [comment]
Le code conseillé pour des emails unique de factory_boy (notre surchouche à faker) semble différent de notre usage : https://factoryboy.readthedocs.io/en/stable/index.html#sequences vs https://github.com/opendatateam/udata/blob/master/udata/core/user/factories.py#L15

**Comment by magopian** [comment]
Zut, c'est un duplicat de #1436 😬
