### ISSUE TITLE
Rajouter une carte dataservice vers l'API tabular API sur les datasets avec des ressources apéifiées

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1467]
Se baser OU copier la logique [can_explore_dataset](https://github.com/opendatateam/udata-tabular-preview/blob/25ee53d39388e8f76e81f121400d934ffb7a86d1/udata_tabular_preview/views.py#L20) de udata-tabular-preview pour décider l'affichage d'une carte DataService ou non.

La fiche dataservice pour tabular API n'existe pas encore en production (cf. https://github.com/datagouv/data.gouv.fr/issues/1497), elle serait à créer et pourrait être un id à configurer (à l'image de [EXPORT_CSV_DATASET_ID](https://github.com/opendatateam/udata/blob/da594f6a8e3202037dfbc9f992cdcf37f47261e1/docs/adapting-settings.md?plain=1#L185) par exemple).

**Comment by ThibaudDauce** [comment]
@maudetes @nicolaskempf57

Je vois trois implémentations possibles :
1. Hard-coder une carte statique dans la liste des dataservices (ça implique de jouer sur le `count` en haut de la page et de ne pas avoir des données dynamique si on modifie la disponibilité / mise à jour / description…)
2. Faire une nouvelle requête pour fetch un dataservice avec l'ID spécifié dans la config (plus lent, toujours obligé de jouer avec le `count` en haut de la page, peut poser des problèmes de sauts d'écran lors du chargement différé de cet endpoint)
3. Mettre le dataservice spécial directement depuis le backend dans les différents endpoints qui en ont besoin (une seule requête, disponible également via API, mais peut-être plus compliqué à gérer…)

**Comment by ThibaudDauce** [comment]
Nouvelle question implémentation, on a statué sur le fait que l'on allait créer un unique dataservice data.gouv.fr qui regroupera les milliers de datasets référencé. Cela permet de « tester » ce genre de dataservice (qu'on aura peut-être un jour) et d'être plus résiliant sur le sujet. En plus ça permet d'avoir un système le plus propre possible avec le moins de code custom.

Maintenant je me pose la question de comment mettre en valeur ce dataservice sur le front (changement d'icône et changement de couleur de bordure [voir Figma](https://www.figma.com/design/9Ai2c1JrRyFNKDSJOXN9wM/%F0%9F%92%BB-Api-et-donn%C3%A9es-restreintes?node-id=956-6194&node-type=frame&t=4egicjoMvUbYC9OF-0)). Je pense utiliser une variable d'environnement du style `FEATURES_DATASETS=['66fa5ad86e1f81fc96474241']` qui permettrait :
1. Côté backend, toujours les retourner un premier dans les listes de résultats
2. Côté frontend, faire les quelques changements de design.

Je me pose quelques questions :
- Le terme `FEATURED` me pose problème car il correspond déjà à un concept existant dans le code…
- Est-ce que justement on ne pourrait pas utiliser le flag `featured` existant ? Seuls les admins peuvent le modifier, non ?
- Ou alors est-ce qu'on trouve un autre nom pour la variable d'environnement ?

**Comment by maudetes** [comment]
Clos par https://github.com/datagouv/udata-front/pull/548, https://github.com/datagouv/udata-front/pull/560 et https://github.com/opendatateam/udata/pull/3156.

La question de la mise en avant de certaines APIs reste ouverte mais fera l'objet d'un ticket dédié et doit aussi être pensé sur la [recherche de dataservice](https://github.com/datagouv/data.gouv.fr/issues/1405)
