### ISSUE TITLE
[Base Sirene des entreprises et de leurs établissements] Le champ `denominationUniteLegale` excède la longueur maximale dans le fichier du 01 Septembre 2024

### ISSUE THREAD

**Issue by said-ibrihen-orange** [datagouv/data.gouv.fr#1477]
## Description du bug
Dans le fichier du [01 Septembre 2024](https://www.data.gouv.fr/fr/datasets/r/0651fb76-bcf3-4f6a-a38d-bc04fa708576), le champ `denominationUniteLegale` dépasse la longueur maximale spécifiée de 120 caractères, cela concerne l'établissement avec le SIRET `93223213500016`. Il est possible que ce problème concerne aussi d'autres établissements.

**Détails :**  
- **Valeur actuelle :**  
  `COMITE DES OEUVRES SOCIALES DES AGENTS DE LA VILLE DE HAM, DU CENTRE COMMUNAL D'ACTION SOCIALE ET DE LA COMMUNAUTE DE COM` (121 caractères)
  
- **Spécification :**  
  Selon la [documentation](https://sirene.fr/static-resources/htm/v_sommaire_311.htm#11), la longueur maximale doit être de 120 caractères.

## Comment reproduire le bug
Deux possibilités : 

1. Récupérer le fichier du  [01 Septembre 2024](https://www.data.gouv.fr/fr/datasets/r/0651fb76-bcf3-4f6a-a38d-bc04fa708576) et y rechercher l'établissement avec le SIRET  `93223213500016`

2. Rechercher l'établissement directement via son SIRET en passant par l'API :

```bash
curl -X GET \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer XXXXX' \
  'https://api.insee.fr/entreprises/sirene/V3.11/siret/93223213500016'
```
## Comportement attendu
Le champ `denominationUniteLegale` doit avoir une longueur inférieure ou égale a 120 caractères.

**Comment by maudetes** [comment]
Nous vous remercions de nous avoir contactés.

Ce canal de support est dédié aux demandes relatives à la plateforme data.gouv.fr. L'équipe de [data.gouv.fr](http://data.gouv.fr/) n'est pas responsable des données publiées sur la plateforme.

Nous vous conseillons de contacter directement le producteur des données (dans l'onglet Discussions du jeu de données concerné). Les producteurs seront capables de répondre à votre question.
