### ISSUE TITLE
Carte API Hydra

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1495]
Affichage différencié de la carte API Hydra

[**Voir le design**](https://www.figma.com/design/9Ai2c1JrRyFNKDSJOXN9wM/%F0%9F%92%BB-Api-et-donn%C3%A9es-restreintes?node-id=968-29226&t=wpoeEaj15CGK0eFF-4)

![image](https://github.com/user-attachments/assets/3117eb83-0ed6-4ee7-8a2a-13d2936643af)

**Comment by nicolaskempf57** [comment]
Done in https://github.com/datagouv/udata-front/pull/548
