### ISSUE TITLE
Tooltip "schéma" sur les ressources dépasse à gauche

### ISSUE THREAD

**Issue by AurelienC** [datagouv/data.gouv.fr#1501]
## Description du bug
Le nouveau tooltip sur les ressources d'un jeu de données qui permet de vérifier le statut de la validation Validata est hors page sur une vue de largeur faible.
<img width="565" alt="Capture d’écran 2024-09-25 à 11 20 59" src="https://github.com/user-attachments/assets/225a9c1a-a619-47b5-804e-89f014b8076a">

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller sur un jeu de données avec une ressource associée à un schéma ([exemple](https://www.data.gouv.fr/fr/datasets/perimetre-zfe-zones-a-faibles-emissions-sur-le-territoire-d-annemasse-agglomeration/))
2. Cliquer sur le bouton "info" du schéma d'une ressource
3. Agrandir/réduire la largeur de la fenêtre du navigateur
4. Constater que le tooltip se positionne à gauche et dépasse lorsque la largeur de la page est réduite

## Comportement attendu
Le tooltip est constamment visible quelque soit la largeur de la page.

**Comment by AurelienC** [comment]
Je rajoute dans ce même ticket ce problème de recouvrement lorsqu'il n'y a qu'une ressource et que le nom du schéma est un peu long :
<img width="453" alt="image" src="https://github.com/user-attachments/assets/894ef32a-f93d-4c99-9d9f-87c89ec20a9f">

Visible ici : https://www.data.gouv.fr/fr/datasets/lieux-de-covoiturage-organisation-direction-departementale-des-territoires-orne/#/resources

**Comment by nicolaskempf57** [comment]
Exact, on a le problème sur les écrans entre 730px et 1300px, on va regarder ça, merci 🙏🏻 

Pour le débordement, c'est un effet de bord des onglets du DSFR, on a prévu de refaire le système dans #1442 donc on devrait le corriger en même temps.
