### ISSUE TITLE
Fixes V1 de L'admin 

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1521]
# General
- [ ] #1619
- [x] Réduire l'écart entre le sous-titre et le tableau (20 sur les maquettes)
- [x] https://github.com/datagouv/data.gouv.fr/issues/1447

# Menu
- [x] En fonction de l’item du menu latéral, ce dernier est plus au moins grand alors qu’il ne devrait pas bouger

# Jeux de données
- [x] Fixer la largeur des colonnes
- [x] Rendre les colonnes fichiers et metrics de la même taille

# Réutilisation
- [ ] Fixer les tailles des colonnes

# Discussions
- [ ] Agrandir la largeur de la première colonne, fixer les autres
- [x] Aligner correctement l'icône des membres dans la colonne dernier commentaires
- [x] Remplacer “Fermée à” par “Fermée le”
- [x] Remplacer “URL” par “Lien vers la discussion”

# Membres
- [x] Corriger l'alignement de l'icône mail
- [ ] Fixer la largeur des colonnes
- [ ] Réduire la largeur de la colonne action au minimum et enlever son intitulé

# Moissonneurs
- [ ] Fixer la largeur des colonnes

# Ressources communautaires
- [x] Ajouter une indication sur l'objet concerné
- [x] Statut ?

# Profil
- [x] Inverser les indications entre SIGLE et SIRET dans l'aide
- [x] Agrandir le champ de description par défaut

**Comment by nicolaskempf57** [comment]
> * [ ]  Prévoir une version responsive (design)

On pourra regarder pour implémenter ou du moins se rapprocher des tailles des colonnes quand on verra un peu mieux les designs pour les 4 ou 5 breakpoints du DSFR

**Comment by nicolaskempf57** [comment]
> * [ ]  Agrandir le champ de description par défaut

J'en ai profité pour le changer en éditeur markdown

**Comment by nicolaskempf57** [comment]
Responsive et tailles de colonnes déplacées dans des tickets séparés
