### ISSUE TITLE
Permettre la vérification de lien Mastodon

### ISSUE THREAD

**Issue by cedricr** [datagouv/data.gouv.fr#1544]
Le réseau social Mastodon permet de [valider les liens insérés](https://docs.joinmastodon.org/user/profile/#verification) dans le profil utilisateur, à partir du moment où la destination de ces liens contient un lien en retour vers le profil de la forme
`<a href="https://social.example.com/@username" rel="me">Whatever</a>`

Github, par exemple, a rajouté ce rel="me" en [fevrier 2023](https://github.blog/changelog/2023-02-02-add-more-social-links-to-your-user-profile/), exactement pour ce cas d’usage ("with special support for popular platforms").

Documentation pour le mot clé `rel` de l’attribut `rel` : https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/me

Les pages de profil utilisateur `https://www.data.gouv.fr/fr/users/<username>/` seraient un exemple parfait pour l’usage de `rel=me`,

**Comment by nicolaskempf57** [comment]
@cedricr j'ai transféré l'issue sur notre dépot dédié aux issues

**Comment by cedricr** [comment]
Merci @nicolaskempf57 !

**Comment by cedricr** [comment]
:pray:
