### ISSUE TITLE
[hydra] Veut-on désactiver l'export parquet pour des fichiers très peu volumineux ?

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1547]
En effet, un certain nombre de fichier sont des CSV très peu volumineux et avec peu de lignes sur data.gouv.fr.
C'est par exemple le cas des fichiers concernant les schémas de véhicule à faible emission ([exemple](https://www.data.gouv.fr/fr/datasets/part-des-vehicules-a-faibles-emissions-dans-le-renouvellement-dun-parc-organisation-ministere-de-la-transition-ecologique-2/#/resources/00414cad-a663-4f63-8b55-b6d3399e5021)).
Pour un fichier CSV de 1.2Ko, le parquet en fait 20.7Ko. Son orientation colonne est de plus peu pertinente.

Cependant, le fait de désactiver cet export implique :
* moins d'homogénéité
* **pas possibilité de passer par un explore basé sur Parquet plutôt que DB postgres**

**Comment by bolinocroustibat** [comment]
Yes, let's not parquetify under 100 lines CSV.
