### ISSUE TITLE
Rajouter une métadonnée documentation métier sur les dataservices

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1561]
Propriété de type URL, ex: `business_documentation`.
Qui sera à afficher notamment sur le front. Cf https://github.com/datagouv/udata-front/pull/575#discussion_r1829304682

Wording à valider, et mettre udata-front à jour en fonction

**Comment by geoffreyaldebert** [comment]
`business_documentation_url` me semble adapté.
