### ISSUE TITLE
Mettre en place bandeau enquête annuelle

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1600]
🇫🇷 
Aidez nous à améliorer data.gouv.fr en répondant à notre **[enquête annuelle](https://tally.so/r/nP28Db)** ❤️

🇬🇧 
Help us improve data.gouv.fr : take a moment to answer our **[annual survey](https://tally.so/r/nP28Db)** ❤️ 

🇪🇸 
¡Ayúdanos a mejorar data.gouv.fr! Responde a nuestra **[encuesta anual](https://tally.so/r/nP28Db)** ❤️

**Comment by maudetes** [comment]
Le bandeau est [live](https://www.data.gouv.fr/)
