### ISSUE TITLE
Repenser la fonctionnalité de signalement

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#381]
Créé par @abulte

**Comment by agarrone** [comment]
Il s'agit de la fonctionnalité de signalement ? Je renomme.

**Comment by abulte** [comment]
👻 👻 

Différent du signalement (eg spam ou autre "gros" problème) je crois, on pouvait signaler des anomalies sur les données, ie "problème de coordonnées à la ligne 312". Une sorte de discussion spécifique.

**Comment by agarrone** [comment]
Voir https://github.com/datagouv/data.gouv.fr/issues/1376
