### ISSUE TITLE
Utiliser mongomock pour les tests

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#467]
Voir ticket https://github.com/mongomock/mongomock/issues/719.

**Comment by agarrone** [comment]
@maudetes Peut-on clore ?

**Comment by maudetes** [comment]
Non, c'est toujours d'actualité ! A voir si des avancées ont résolu le problème côté mongomock :)

**Comment by agarrone** [comment]
@maudetes ?

**Comment by maudetes** [comment]
Toujours d'actualité, mais comme le ticket référencé côté mongomock n'a pas avancé, je clos pour l'instant.
A réouvrir si l'opérateur `$text` est finalement implémenté dans mongomock.
