### ISSUE TITLE
Enquêter sur de nouveaux problèmes d'intégrité 🎉 

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#478]
Voir https://sentry.data.gouv.fr/organizations/sentry/issues/12120/?project=5&query=metrics&statsPeriod=14d sur la prod
Voir https://sentry.data.gouv.fr/organizations/sentry/issues/13436/?project=12&query=metrics&statsPeriod=14d sur staging
Problème d'intégrité de metrics?

___
**Edit**: voir dernier message de ce ticket pour un ticket d'actu

**Comment by abulte** [comment]
This one https://sentry.data.gouv.fr/organizations/sentry/issues/12120/?project=5&query=metrics&statsPeriod=14d is a `Reuse` linked to a non existing `Dataset`. Trying to fetch the `id` attribute was obviously not enough, at least in this case.

See below the difference between a correctly linked Dataset and a wrongful one. A test based on `_DBRef__database` attribute might be generic enough on all models.

```
>>> r = Reuse.objects.get(slug='snails-production-and-trade-in-france')
>>> [d.id for d in r.datasets]
[ObjectId('53699906a3a729239d20511a')]
>>> [d.title for d in r.datasets]
Traceback (most recent call last):
  File "/srv/udata/lib/python3.7/site-packages/bson/dbref.py", line 83, in __getattr__
    return self.__kwargs[key]
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "<console>", line 1, in <listcomp>
  File "/srv/udata/lib/python3.7/site-packages/bson/dbref.py", line 85, in __getattr__
    raise AttributeError(key)
AttributeError: title
>>> d = r.datasets[0]
>>> d
DBRef('dataset', ObjectId('53699906a3a729239d20511a'))
>>> d.__dict__
{'_DBRef__collection': 'dataset', '_DBRef__id': ObjectId('53699906a3a729239d20511a'), '_DBRef__database': None, '_DBRef__kwargs': {}}
```

```
>>> r = Reuse.objects.first()
>>> d = r.datasets[0]
>>> d.__dict__
{'_cls': 'Dataset', 'get_frequency_display': functools.partial(<bound method BaseDocument.__get_field_display of <Dataset: Aménagements cyclables France Métropolitaine>>, field=<mongoengine.fields.StringField object at 0x7f228740cc50>)}
```

**Comment by maudetes** [comment]
L'erreur sur la [home de staging]https://sentry.data.gouv.fr/organizations/sentry/issues/13436/?project=12&query=metrics&statsPeriod=14d() n'a pas l'air d'être en lien avec les soucis d'intégrité, mais il s'agirait *probablement* plutôt d'une erreur liée à la descente de prod sur laquelle `metrics.bson` avait été supprimé. En refaisant une descente avec `metrics.bson`, le soucis a été résolu.

**Comment by maudetes** [comment]
la date de la réutilisation (id=53f32da1a3a72908bd9dfc12) sur laquelle il y a un soucis d'intégrité: 19-08-2014 vs la date de l'ajout de la reverse rule correspondante: 17-10-2014 https://github.com/opendatateam/udata/blob/4a8f3cfcd5e707e67094a360dfbf246a6b75845c/udata/core/reuse/models.py. Il semble qu'il s'agisse bien d'une vieille erreur d'intégrité.

**Comment by agarrone** [comment]
@maudetes tjr d'actu ?
