### ISSUE TITLE
Créa et intégration mails

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#498]
Créa mail dans le style de la refonte graphique

@maudetes tu as des screen pour @rkalfane ?

**Comment by maudetes** [comment]
Les différentes templates mails sont présentés ci-dessous.
@quaxsze, est-ce que tu confirmes que les vues ont été copiées côté udata-front, mais sont encore utilisées côté udata seulement ?
Qu'est-ce que tu penses d'utiliser les hooks, comme ce qui avait été fait sur https://github.com/opendatateam/udata/pull/2671 pour les themer côté udata-front ?

account_deleted
![image](https://user-images.githubusercontent.com/28541902/144037783-f79e0873-df68-46e2-9079-32c6930e0fae.png)

badge_added_certified
![image](https://user-images.githubusercontent.com/28541902/144037918-7234b955-17b8-4b1f-9bdb-2f5eae1c95cf.png)

badge_added_public_service
![image](https://user-images.githubusercontent.com/28541902/144037993-e6bbb548-1214-4da2-a6df-ebe8c9faa640.png)

discussion_closed
![image](https://user-images.githubusercontent.com/28541902/144038149-3fecde59-499a-4770-aa17-f48b2400dc9f.png)

frequency_reminder
![image](https://user-images.githubusercontent.com/28541902/144039295-60b58471-a2d5-4675-bca9-966c14be9bd6.png)

membership_refused
![image](https://user-images.githubusercontent.com/28541902/144039675-cac9f645-d652-4f83-b8a0-a9fcd837643a.png)

membership_request
![image](https://user-images.githubusercontent.com/28541902/144041693-f4f6577d-dafa-463b-b55f-23e746c3a7b3.png)

new_discussion_comment
![image](https://user-images.githubusercontent.com/28541902/144040447-b5e4e4ff-1021-40fd-812d-ce17cce4aaee.png)

new_discussion
![image](https://user-images.githubusercontent.com/28541902/144040570-f4740ca2-c5c7-4066-9857-5c8048c125b6.png)

new_follower_org
![image](https://user-images.githubusercontent.com/28541902/144040892-6d953c33-7d27-4c35-ada8-a5a2e0eedcfc.png)

new_follower
![image](https://user-images.githubusercontent.com/28541902/144040975-9e255ca4-82ed-49db-8054-69199ffba9d0.png)

new_member
![image](https://user-images.githubusercontent.com/28541902/144041102-502c4e9b-0c78-4adc-b9d3-76c181366a48.png)

new_reuse
![image](https://user-images.githubusercontent.com/28541902/144041264-8dcd8961-98f8-4503-a70f-2c124a8f1389.png)

**Comment by quaxsze** [comment]
Oui je pense que c'est une bonne idée, d'appliquer ce mécanisme pour les garder coté data et les thèmes coté data-front.

**Comment by agarrone** [comment]
Maquettes prêtes à retravailler en fonction

**Comment by maudetes** [comment]
La liste des mails de sécurité existants aujourd'hui

`Bienvenue`
![image](https://github.com/user-attachments/assets/446bbbce-8479-4ef3-a77e-f6df27873ef5)

`Bienvenue` (compte existant)
![image](https://github.com/user-attachments/assets/589eb349-2fc2-493f-9276-978982e27450)

`Veuillez confirmer votre adresse e-mail` & `Instructions pour confirmer le changement d'email`
![image](https://github.com/user-attachments/assets/6308f219-2e49-42c0-9377-4c755e958941)

`Instructions de réinitialisation du mot de passe`
![image](https://github.com/user-attachments/assets/d8d748eb-cc7d-4157-beca-717248e37054)

`Votre mot de passe a été réinitialisé`
![image](https://github.com/user-attachments/assets/769f0401-8267-4f59-8ac3-98b5c6055380)

`Votre mot de passe a été modifié`
![image](https://github.com/user-attachments/assets/1c8009de-e7ad-4370-933d-517a2cb36929)
