### ISSUE TITLE
Move schema logic back to plugin

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#609]
Schema has been moved to udata-front following udata 3 refactoring. See https://github.com/etalab/udata-gouvfr/pull/571.

It was then moved in the Vue side of udata-front following [resource refactoring](https://github.com/etalab/udata-front/pull/30).

Move schema logic back to the [udata-schema-gouvfr](https://github.com/etalab/udata-schema-gouvfr) plugin.

**Comment by agarrone** [comment]
@maudetes d'actu ?

**Comment by maudetes** [comment]
Ca n'a pas été implémenté, mais le besoin de bouger schema dans un plugin ne s'est pas fait ressentir depuis.
