### ISSUE TITLE
UI Kit consolidation : Primary button

### ISSUE THREAD

**Issue by nicolaskempf57** [datagouv/data.gouv.fr#686]
This thing is used in many places but not any important ones : preview modal, schema modal, oauth form, schema modal button, top of the page error section (base.html), register / login form and "sysadmin" button.
It exists in 18+ shades but is only used in its default color 😅
I think we can easily delete the colored variants and even start replacing it in older templates with the DSFR button if we want to but the style is quite different.

👉 https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217284660/Boutons+-+Buttons

**Comment by nicolaskempf57** [comment]
Les variations sont supprimées.
On avait évoqué la suppression du bouton primaire mais je ne suis pas sûr que ce soit encore d'actualité.

**Comment by agarrone** [comment]
@nicolaskempf57  on peut clore ce ticket ?

**Comment by nicolaskempf57** [comment]
Oui, on a gardé le bouton primaire dans les designs, donc plus besoin de garder ce ticket.
