### ISSUE TITLE
Explore : Investiguer pourquoi certains fichiers ne fonctionne pas

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#964]
Par exemple : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2Ff868cca6-8da1-4369-a78d-47463f19a9a3

Autre exemple : pas de lignes : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2F2824df12-c542-4250-97f4-d6e566f69ef1

Mauvais parsing des colonnes : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2Fb7cd2cec-7964-488c-b3ad-837d55413988

Erreur non identifiée, alors que la previz fonctionne : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2F746560ae-4328-43f1-b917-9e28891b28d9

Téléchargement sur filtres ne fonctionne pas : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2Fd6df4e06-d55c-4616-a974-2b53d0d4e025&fonction__exact=Premier%20ministre

Catalogue des organisations sur data.gouv.fr: https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2Fb7bbfedc-2448-4135-a6c7-104548d396e7 (la previz échoue auss)

Soucis sur la virgule qui saute sur ce CSV (colonne `loypredm2`) : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2Fdfb542cd-a808-41e2-9157-8d39b5c24edb

**Comment by nicolaskempf57** [comment]
Pour info, dans le cas du fichier des loyers, CSVAPI nous retourne le résultat sans virgule

**Comment by geoffreyaldebert** [comment]
Je reprends les signalements en indicants les pages datasets sinon c'est compliqué d'investiguer : 

Par exemple : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2Ff868cca6-8da1-4369-a78d-47463f19a9a3
Dataset : https://www.data.gouv.fr/fr/datasets/5d13a8b6634f41070a43dff3/
Resource : export-dataset-20221219-064630.csv
Cela a marché en local chez moi.. J'ai poussé la base sqlite sur la prod. Mais pas possible de comprendre ce qu'il s'est passé.. Problème niveau serveur je suppose. 

Autre exemple : pas de lignes : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2F2824df12-c542-4250-97f4-d6e566f69ef1
dataset : https://www.data.gouv.fr/fr/datasets/62eb0ecc55e3904e620505d1/ 
resource : Export au format CSV 
Ca marche chez moi..

Mauvais parsing des colonnes : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2Fb7cd2cec-7964-488c-b3ad-837d55413988
dataset : https://www.data.gouv.fr/fr/datasets/55716fe9c751df588de5726a/
resource : Export au format CSV
Problème agate. Agate n'interprète pas bien les colonnes (sans doute dû au premier caractère des lignes qui est un `{`). csv-detective et pandas n'a pas ce problème. Besoin d'une rationalisation des outils de parsing entre agate et pandas (ou autre). 

Erreur non identifiée, alors que la previz fonctionne : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2F746560ae-4328-43f1-b917-9e28891b28d9
datasets : https://www.data.gouv.fr/fr/datasets/636c694f2caac75716f64c85/
resource : export csv
La previz fonctionne car c'est la previz ODS. La previz ne fonctionne pas avec la preview data.gouv.fr
Le fichier est gros et très lent à télécharger.

Téléchargement sur filtres ne fonctionne pas : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2Fd6df4e06-d55c-4616-a974-2b53d0d4e025&fonction__exact=Premier%20ministre
Ca marche chez moi...

Catalogue des organisations sur data.gouv.fr: https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2Fb7bbfedc-2448-4135-a6c7-104548d396e7 (la previz échoue auss)
Le csv est pas très propre. Il faudrait soigner l'export notamment au niveau des longs textes car ceux-ci prennent plusieurs lignes dans le csv. Agate ne l'interprète pas bien. Côté pandas et csv-detective ça marche.

Soucis sur la virgule qui saute sur ce CSV (colonne loypredm2) : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2Fdfb542cd-a808-41e2-9157-8d39b5c24edb
Problème parsing agate table. Pandas et csv-detective sont ok.
