### ISSUE TITLE
Développements : Mise à plat de l'export du catalogue data.gouv.fr

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#979]
Voir pour améliorer les headers des catalogues https://www.data.gouv.fr/fr/datasets/catalogue-des-donnees-de-data-gouv-fr/.

Standardiser les séparateurs des noms de colonne, ex `metrics.views`, rajouter les infos manquantes, etc.
Mieux documenter le jeu de données.

Comprendre pourquoi il y a un soucis lors de l'explore sur le catalogue organisation.

Quelques infos en vrac à rajouter :
* les thématiques des réutilisations
* les schémas des ressources

**Comment by agarrone** [comment]
@Pierlou Chaud de jeter un oeil à l'occasion ?

**Comment by Pierlou** [comment]
Yes, je veux bien le lien des codes qui génèrent les exports svp 🙏

**Comment by agarrone** [comment]
@maudetes ?

**Comment by maudetes** [comment]
Je pense qu'il faut mettre à plat l'état actuel et les besoins de modif par contre. Et si possible (:crossed_fingers:) éviter de casser le nom des colonnes pour s'éviter d'impacter des réutilisateurs de ces JDDs (Pierlou inclu).

Quelques pointeurs de code :
* La tâche de génération : https://github.com/maudetes/udata/blob/4abbb0901d5407843a768ea4cc89b16243718b06/udata/core/dataset/tasks.py#L159
* Les colonnes sont définies dans les fichiers `csv.py` des différents modèles : https://github.com/maudetes/udata/blob/master/udata/core/dataset/csv.py
* Le modèle de base pour la cataloguisation en CSV : https://github.com/maudetes/udata/blob/master/udata/frontend/csv.py

Possible que le problème des orgas ait été réglé par effet de bord de https://github.com/opendatateam/udata/pull/2818.

**Comment by Pierlou** [comment]
Initié [ici](https://github.com/opendatateam/udata/pull/3052), chaud pour des retours/suggestions 🙏
